from pathlib import Path
p = Path('/root/apptv/App.tsx')
text = p.read_text(encoding='utf-8')
text = text.replace(
"                          onPointerDown={(event) => {\n                            event.stopPropagation();\n                            startSeekHold(-10);\n                          }}\n                          onPointerUp={(event) => {\n                            event.stopPropagation();\n                            endSeekHold(-10);\n                          }}\n                          onPointerLeave={() => clearSeekHold()}\n                          onPointerCancel={() => clearSeekHold()}\n",
"                          onMouseDown={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            startSeekHold(-10);\n                          }}\n                          onMouseUp={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            endSeekHold(-10);\n                          }}\n                          onMouseLeave={() => clearSeekHold()}\n                          onTouchStart={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            startSeekHold(-10);\n                          }}\n                          onTouchEnd={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            endSeekHold(-10);\n                          }}\n                          onTouchCancel={() => clearSeekHold()}\n"
)
text = text.replace(
"                          onPointerDown={(event) => {\n                            event.stopPropagation();\n                            startSeekHold(10);\n                          }}\n                          onPointerUp={(event) => {\n                            event.stopPropagation();\n                            endSeekHold(10);\n                          }}\n                          onPointerLeave={() => clearSeekHold()}\n                          onPointerCancel={() => clearSeekHold()}\n",
"                          onMouseDown={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            startSeekHold(10);\n                          }}\n                          onMouseUp={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            endSeekHold(10);\n                          }}\n                          onMouseLeave={() => clearSeekHold()}\n                          onTouchStart={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            startSeekHold(10);\n                          }}\n                          onTouchEnd={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            endSeekHold(10);\n                          }}\n                          onTouchCancel={() => clearSeekHold()}\n"
)
p.write_text(text, encoding='utf-8')
print('patched-seek-hold-mouse-touch')
