from pathlib import Path
p = Path('/root/apptv/App.tsx')
text = p.read_text(encoding='utf-8')

text = text.replace(
"  const clearSeekHold = useCallback(() => {\n    if (seekHoldDelayTimerRef.current) {\n      window.clearTimeout(seekHoldDelayTimerRef.current);\n      seekHoldDelayTimerRef.current = null;\n    }\n    if (seekHoldRepeatTimerRef.current) {\n      window.clearInterval(seekHoldRepeatTimerRef.current);\n      seekHoldRepeatTimerRef.current = null;\n    }\n  }, []);\n\n  const startSeekHold = useCallback((deltaSeconds: number) => {\n    clearSeekHold();\n    seekHoldTriggeredRef.current = false;\n\n    seekHoldDelayTimerRef.current = window.setTimeout(() => {\n      seekHoldDelayTimerRef.current = null;\n      seekHoldTriggeredRef.current = true;\n      seekExpandedPlayback(deltaSeconds);\n      seekHoldRepeatTimerRef.current = window.setInterval(() => {\n        seekExpandedPlayback(deltaSeconds);\n      }, 160);\n    }, 260);\n  }, [clearSeekHold, seekExpandedPlayback]);\n\n  const endSeekHold = useCallback((deltaSeconds: number) => {\n    const triggered = seekHoldTriggeredRef.current;\n    clearSeekHold();\n    seekHoldTriggeredRef.current = false;\n    if (!triggered) {\n      seekExpandedPlayback(deltaSeconds);\n    }\n  }, [clearSeekHold, seekExpandedPlayback]);\n",
"  const clearSeekHold = useCallback(() => {\n    if (seekHoldDelayTimerRef.current) {\n      window.clearTimeout(seekHoldDelayTimerRef.current);\n      seekHoldDelayTimerRef.current = null;\n    }\n    if (seekHoldRepeatTimerRef.current) {\n      window.clearInterval(seekHoldRepeatTimerRef.current);\n      seekHoldRepeatTimerRef.current = null;\n    }\n    window.removeEventListener('mouseup', window.__wiipynSeekHoldRelease as any);\n    window.removeEventListener('touchend', window.__wiipynSeekHoldRelease as any);\n    window.removeEventListener('touchcancel', window.__wiipynSeekHoldRelease as any);\n    window.__wiipynSeekHoldRelease = undefined;\n  }, []);\n\n  const endSeekHold = useCallback((deltaSeconds: number) => {\n    const triggered = seekHoldTriggeredRef.current;\n    clearSeekHold();\n    seekHoldTriggeredRef.current = false;\n    if (!triggered) {\n      seekExpandedPlayback(deltaSeconds);\n    }\n  }, [clearSeekHold, seekExpandedPlayback]);\n\n  const startSeekHold = useCallback((deltaSeconds: number) => {\n    clearSeekHold();\n    seekHoldTriggeredRef.current = false;\n\n    const release = () => endSeekHold(deltaSeconds);\n    window.__wiipynSeekHoldRelease = release;\n    window.addEventListener('mouseup', release, { once: true });\n    window.addEventListener('touchend', release, { once: true });\n    window.addEventListener('touchcancel', release, { once: true });\n\n    seekHoldDelayTimerRef.current = window.setTimeout(() => {\n      seekHoldDelayTimerRef.current = null;\n      seekHoldTriggeredRef.current = true;\n      seekExpandedPlayback(deltaSeconds);\n      seekHoldRepeatTimerRef.current = window.setInterval(() => {\n        seekExpandedPlayback(deltaSeconds);\n      }, 140);\n    }, 220);\n  }, [clearSeekHold, endSeekHold, seekExpandedPlayback]);\n"
)

text = text.replace(
"                          onMouseUp={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            endSeekHold(-10);\n                          }}\n                          onMouseLeave={() => clearSeekHold()}\n                          onTouchStart={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            startSeekHold(-10);\n                          }}\n                          onTouchEnd={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            endSeekHold(-10);\n                          }}\n                          onTouchCancel={() => clearSeekHold()}\n",
"                          onMouseUp={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            endSeekHold(-10);\n                          }}\n                          onTouchStart={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            startSeekHold(-10);\n                          }}\n                          onTouchEnd={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            endSeekHold(-10);\n                          }}\n                          onTouchCancel={() => clearSeekHold()}\n"
)

text = text.replace(
"                          onMouseUp={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            endSeekHold(10);\n                          }}\n                          onMouseLeave={() => clearSeekHold()}\n                          onTouchStart={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            startSeekHold(10);\n                          }}\n                          onTouchEnd={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            endSeekHold(10);\n                          }}\n                          onTouchCancel={() => clearSeekHold()}\n",
"                          onMouseUp={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            endSeekHold(10);\n                          }}\n                          onTouchStart={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            startSeekHold(10);\n                          }}\n                          onTouchEnd={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                            endSeekHold(10);\n                          }}\n                          onTouchCancel={() => clearSeekHold()}\n"
)

if 'window.__wiipynSeekHoldRelease' not in text:
    text = text.replace(
"import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react';\n",
"import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react';\n\ndeclare global {\n  interface Window {\n    __wiipynSeekHoldRelease?: (() => void) | undefined;\n  }\n}\n"
)

p.write_text(text, encoding='utf-8')
print('patched-seek-hold-global-release')
