from pathlib import Path
p = Path('/root/apptv/App.tsx')
text = p.read_text(encoding='utf-8')

text = text.replace(
"  const expandedInfoTimerRef = useRef<number | null>(null);\n  const playbackAdvanceTimerRef = useRef<number | null>(null);\n",
"  const expandedInfoTimerRef = useRef<number | null>(null);\n  const playbackAdvanceTimerRef = useRef<number | null>(null);\n  const seekHoldDelayTimerRef = useRef<number | null>(null);\n  const seekHoldRepeatTimerRef = useRef<number | null>(null);\n  const seekHoldTriggeredRef = useRef(false);\n"
)

text = text.replace(
"  const seekExpandedPlayback = useCallback((deltaSeconds: number) => {\n    if (!expandedPlayback) return;\n    if (expandedPlayback.playback.item.type !== ContentType.VIDEO) return;\n\n    const currentOffset = getExpandedEffectiveOffset(expandedSeekAnchor, expandedPlayback.playback, Date.now());\n    const nextOffset = Math.min(\n      clampExpandedOffset(expandedPlayback.playback.item, currentOffset + deltaSeconds),\n      getExpandedMaxOffset(expandedPlayback.channelIndex, expandedPlayback.playback),\n    );\n\n    setExpandedSeekAnchor({\n      channelIndex: expandedPlayback.channelIndex,\n      playbackIndex: expandedPlayback.playback.index,\n      baseOffset: nextOffset,\n      startedAtMs: Date.now(),\n    });\n    showExpandedInfo();\n  }, [clampExpandedOffset, expandedPlayback, expandedSeekAnchor, getExpandedEffectiveOffset, getExpandedMaxOffset, showExpandedInfo]);\n",
"  const seekExpandedPlayback = useCallback((deltaSeconds: number) => {\n    if (!expandedPlayback) return;\n    if (expandedPlayback.playback.item.type !== ContentType.VIDEO) return;\n\n    const currentOffset = getExpandedEffectiveOffset(expandedSeekAnchor, expandedPlayback.playback, Date.now());\n    const nextOffset = Math.min(\n      clampExpandedOffset(expandedPlayback.playback.item, currentOffset + deltaSeconds),\n      getExpandedMaxOffset(expandedPlayback.channelIndex, expandedPlayback.playback),\n    );\n\n    setExpandedSeekAnchor({\n      channelIndex: expandedPlayback.channelIndex,\n      playbackIndex: expandedPlayback.playback.index,\n      baseOffset: nextOffset,\n      startedAtMs: Date.now(),\n    });\n    showExpandedInfo();\n  }, [clampExpandedOffset, expandedPlayback, expandedSeekAnchor, getExpandedEffectiveOffset, getExpandedMaxOffset, showExpandedInfo]);\n\n  const clearSeekHold = useCallback(() => {\n    if (seekHoldDelayTimerRef.current) {\n      window.clearTimeout(seekHoldDelayTimerRef.current);\n      seekHoldDelayTimerRef.current = null;\n    }\n    if (seekHoldRepeatTimerRef.current) {\n      window.clearInterval(seekHoldRepeatTimerRef.current);\n      seekHoldRepeatTimerRef.current = null;\n    }\n  }, []);\n\n  const startSeekHold = useCallback((deltaSeconds: number) => {\n    clearSeekHold();\n    seekHoldTriggeredRef.current = false;\n\n    seekHoldDelayTimerRef.current = window.setTimeout(() => {\n      seekHoldDelayTimerRef.current = null;\n      seekHoldTriggeredRef.current = true;\n      seekExpandedPlayback(deltaSeconds);\n      seekHoldRepeatTimerRef.current = window.setInterval(() => {\n        seekExpandedPlayback(deltaSeconds);\n      }, 160);\n    }, 260);\n  }, [clearSeekHold, seekExpandedPlayback]);\n\n  const endSeekHold = useCallback((deltaSeconds: number) => {\n    const triggered = seekHoldTriggeredRef.current;\n    clearSeekHold();\n    seekHoldTriggeredRef.current = false;\n    if (!triggered) {\n      seekExpandedPlayback(deltaSeconds);\n    }\n  }, [clearSeekHold, seekExpandedPlayback]);\n"
)

text = text.replace(
"  useEffect(() => {\n    if (!expandedPlayback) {\n      setExpandedSeekAnchor(null);\n      setIsExpandedInfoVisible(false);\n",
"  useEffect(() => {\n    if (!expandedPlayback) {\n      clearSeekHold();\n      seekHoldTriggeredRef.current = false;\n      setExpandedSeekAnchor(null);\n      setIsExpandedInfoVisible(false);\n"
)

text = text.replace(
"  }, [expandedPlayback?.channelIndex, expandedPlayback?.playback.index, expandedPlayback?.playback.offset, showExpandedInfo]);\n",
"  }, [clearSeekHold, expandedPlayback?.channelIndex, expandedPlayback?.playback.index, expandedPlayback?.playback.offset, showExpandedInfo]);\n"
)

text = text.replace(
"                        <button\n                          type=\"button\"\n                          onClick={(event) => {\n                            event.stopPropagation();\n                            seekExpandedPlayback(-10);\n                          }}\n                          className=\"rounded-full border border-white/20 bg-black/55 px-[0.9vw] py-[0.45vw] text-[0.82vw] font-bold text-white/90 hover:bg-black/75\"\n                        >\n                          -10s\n                        </button>\n                        <button\n                          type=\"button\"\n                          onClick={(event) => {\n                            event.stopPropagation();\n                            seekExpandedPlayback(10);\n                          }}\n                          className=\"rounded-full border border-white/20 bg-black/55 px-[0.9vw] py-[0.45vw] text-[0.82vw] font-bold text-white/90 hover:bg-black/75\"\n                        >\n                          +10s\n                        </button>",
"                        <button\n                          type=\"button\"\n                          onPointerDown={(event) => {\n                            event.stopPropagation();\n                            startSeekHold(-10);\n                          }}\n                          onPointerUp={(event) => {\n                            event.stopPropagation();\n                            endSeekHold(-10);\n                          }}\n                          onPointerLeave={() => clearSeekHold()}\n                          onPointerCancel={() => clearSeekHold()}\n                          onClick={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                          }}\n                          className=\"rounded-full border border-white/20 bg-black/55 px-[0.9vw] py-[0.45vw] text-[0.82vw] font-bold text-white/90 hover:bg-black/75\"\n                        >\n                          -10s\n                        </button>\n                        <button\n                          type=\"button\"\n                          onPointerDown={(event) => {\n                            event.stopPropagation();\n                            startSeekHold(10);\n                          }}\n                          onPointerUp={(event) => {\n                            event.stopPropagation();\n                            endSeekHold(10);\n                          }}\n                          onPointerLeave={() => clearSeekHold()}\n                          onPointerCancel={() => clearSeekHold()}\n                          onClick={(event) => {\n                            event.preventDefault();\n                            event.stopPropagation();\n                          }}\n                          className=\"rounded-full border border-white/20 bg-black/55 px-[0.9vw] py-[0.45vw] text-[0.82vw] font-bold text-white/90 hover:bg-black/75\"\n                        >\n                          +10s\n                        </button>"
)

p.write_text(text, encoding='utf-8')
print('patched-seek-hold')
